services:
  - type: web
    name: nad-scanner-backend
    runtime: python
    plan: free
    buildCommand: |
      pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
      pip install gunicorn eventlet
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:$PORT web_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 5000
      - key: PYTORCH_CPU_ONLY
        value: "1"
      - key: DISABLE_SSL
        value: "1"
    healthCheckPath: /
